### ISSUE TITLE
Subsampling Readdy and cytosim data for compression analysis

### ISSUE THREAD

**Issue by mogres** [simularium/subcell-analysis#13]
### Feature Description
We would like to match the number of timepoints as well as the number of monomer points between different simulators. Currently, ReaDDy simulations are sampled at 1001 total timepoints across all velocities while cytosim simulations have variable number of timepoints depending on velocity. The number of monomer points is also different between the two simulators.

### Solution

- [x] Subsample processed cytosim data to 200 timepoints for all velocities
- [x] Subsample processed ReaDDy data to 200 timepoints for all velocities
- [x] Subsample processed cytosim data to 200 monomer points for all velocities
- [x] Subsample processed reaDDy data to 200 monomer points for all velocities

**Comment by mattakamatsu** [comment]
Working! 


![Image](https://github.com/simularium/subcell-analysis/assets/16111930/fb7ad26c-702d-460b-be2b-775c4db6ef5a)


**Next** @kvegesna will run the metric and plot workflow on these subsampled data. and clean up the script  (sub_sample_simulations.py) so that it runs in one go

**Comment by mattakamatsu** [comment]
- [ ] we could (or should) calculate and report the error of the metrics, before vs after subsampling

**Comment by mattakamatsu** [comment]
The above task is now

- [ ] [Issue #20 ](https://github.com/orgs/simularium/projects/8/views/2?pane=issue&itemId=41978224)
