### ISSUE TITLE
Compare compression metrics across simulators

### ISSUE THREAD

**Issue by mogres** [simularium/subcell-analysis#14]
### Feature Description
We want to compare various compression related metrics across readdy and cytosim for different velocities.

### Metrics used

- [x] Non-coplanarity: defined as the ratio of variance explained by the third principal component of the polymer trace
- [x] Peak asymmetry: defined as the relative normalized position of the polymer trace peak (farthest point from the end-to-end axis) along the axis.
- [x] Polymer twist: defined as the sum of consecutive angles between 2D projections of monomer points. Can be a signed or unsigned sum.
- [x] Bending energy?: this would be a rescaling of the unsigned polymer twist
- [ ] Generate final plots

**Comment by mogres** [comment]
1. Non coplanarity
![all_simulators_NON_COPLANARITY_vs_time](https://github.com/simularium/subcell-analysis/assets/101426188/2ca6829f-4ca7-4bcc-946a-fb5a56f698a9)

2. Peak asymmetry
![all_simulators_PEAK_ASYMMETRY_vs_time](https://github.com/simularium/subcell-analysis/assets/101426188/eda586bf-2973-43c6-8da2-7fc4f832af5e)

3. Signed Fiber Twist
![all_simulators_TOTAL_FIBER_TWIST_SIGNED_vs_time](https://github.com/simularium/subcell-analysis/assets/101426188/931f9191-0f92-4495-9725-a1d2a24768ba)

4. Unsigned Fiber Twist
![all_simulators_TOTAL_FIBER_TWIST_vs_time](https://github.com/simularium/subcell-analysis/assets/101426188/54619c9c-e832-4133-8153-a0c61c3cc285)

**Comment by mattakamatsu** [comment]
Bending energy plot! 

![Image](https://github.com/simularium/subcell-analysis/assets/16111930/587bed5d-3825-4a5f-8125-92c8a1374a7c)

**Comment by blairlyons** [comment]
all of these metrics plots have been added to Simularium trajectories: [ReaDDy](https://simularium.github.io/simularium-data-library/readdy.html) and [CytoSim](https://simularium.github.io/simularium-data-library/cytosim.html)
