### ISSUE TITLE
Run a baseline simulation of free actin filaments, in readdy and cytosim

### ISSUE THREAD

**Issue by mattakamatsu** [simularium/subcell-analysis#19]
In order to have a baseline for variance and magnitude of the metrics
we're going to use the time scale conditions for the fastest velocity

**Comment by mattakamatsu** [comment]
We decided to run cytosim simulations with one end attached, to serve as our baseline

**Comment by blairlyons** [comment]
ReaDDy baseline trajectories are listed [here](https://simularium.github.io/simularium-data-library/readdy.html)
Cytosim are listed [here](https://simularium.github.io/simularium-data-library/cytosim.html)
