### ISSUE TITLE
Report wall clock times for the simulations

### ISSUE THREAD

**Issue by mattakamatsu** [simularium/subcell-analysis#30]

**Comment by blairlyons** [comment]
ReaDDy run times are listed [here](https://docs.google.com/spreadsheets/d/16rR78xISr3-Le_D-nX_DJBY1wO_nE45TGFkL0O1QiiU/edit?usp=sharing)

**Comment by blairlyons** [comment]
(whoops still need Cytosim)

**Comment by mogres** [comment]
@kvegesna @blairlyons 

If we do not have the cytosim numbers on hand, would we have to re-run the simulations? Or do you think an approximate range is ok? (Would be good to have more repeats, but depending on how long it takes, that may not be a good idea.)

**Comment by mattakamatsu** [comment]
The simulation times should be in messages.cmo: 
<img width="961" alt="image" src="https://github.com/simularium/subcell-analysis/assets/16111930/f5a48eb2-99cf-4baa-a43a-e53210f97a6f">
