### ISSUE TITLE
Change X axis of plots to absolute time, in µs (for example)

### ISSUE THREAD

**Issue by mattakamatsu** [simularium/subcell-analysis#31]

**Comment by mogres** [comment]
![image](https://github.com/simularium/subcell-analysis/assets/101426188/f655cbdb-ec7e-4428-b75f-b7cce0051bd1)
![image](https://github.com/simularium/subcell-analysis/assets/101426188/fcadfd4b-f8f8-4087-a497-4dd7c67a8bd4)
![image](https://github.com/simularium/subcell-analysis/assets/101426188/56525062-6244-49ec-910a-7945625321cd)
![image](https://github.com/simularium/subcell-analysis/assets/101426188/12c98ea4-7159-4477-89c0-f2abf3954fcd)
![image](https://github.com/simularium/subcell-analysis/assets/101426188/8cda6c20-5612-4f18-91ea-28aa5deedea6)
![image](https://github.com/simularium/subcell-analysis/assets/101426188/180a1510-45ff-4ec5-9293-4a173a24041c)
